//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Filter_Records_Between_Two_Dates.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customer
    {
        public long id { get; set; }
        public string Seel_code { get; set; }
        public string Genders { get; set; }
        public Nullable<System.DateTime> Dates { get; set; }
        public string Positions { get; set; }
        public string Departments { get; set; }
        public string Shirts { get; set; }
        public string T_Shirts { get; set; }
        public string Safety_Shoes { get; set; }
        public string Medical_insurance_card { get; set; }
        public string Business_card { get; set; }
        public string Hijab { get; set; }
    }
}
