//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Filter_Records_Between_Two_Dates.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Genders_samaya
    {
        public long id { get; set; }
        public string Gender { get; set; }
        public bool isChecked { get; set; }
    }
}
